### ISSUE TITLE
Plugin not working in Moto g 3rd generation

### ISSUE THREAD

**Issue by sandeepadiyar** [jamesla/backgroundvideo#10]
Hi,
I am using this plugin from last 6 months, it was working perfectly and was able to fulfill my requirements.
But recently few users of my app have purchased Moto G 3rd generation phone, at which your plugin has stopped working and it also crashes my app.So please help me to resolve this problem.
Looking forward for your response.Thanks in advance.

**Comment by jhayward** [comment]
This will most likely be an invalid setting for the camera - are you able to supply a log of the crash?

**Comment by sandeepadiyar** [comment]
Thanks for your reply. But i am unable to find anything in log, its blank.

**Comment by jhayward** [comment]
closing as it should be solve with the latest version
