### ISSUE TITLE
Unable to build for Android (Cordova 5.4.1) getHeight and getWidth deprecated

### ISSUE THREAD

**Issue by RomeoInc** [jamesla/backgroundvideo#13]
I have installed the plugin (cordova plugin add io.iclue.backgroundvideo). However, when I attempt to rebuild the project for android, I receive an error regarding CordovaWebView - it appears that both the getHeight() and getWidth() functions no longer exist within CordovaWebView as of Cordova 4.1.1.

Would it be possible to update the plugin to reflect the latest version of Cordova?

Machine Specs:
Cordova CLI: 5.4.1
Gulp version:  CLI vers
Gulp local:   Local ver
Ionic Version: 1.2.1
Ionic CLI Version: 1.7.
Ionic App Lib Version:
OS: Windows 8.1
Node Version: v4.2.3

**Comment by RomeoInc** [comment]
The issue exists in the Cordova plugin - if you manually copy the latest git version of the plugin the issue is resolved. I will keep this issue open however as the issue exists in the Cordova plugin

**Comment by jamesla** [comment]
Ok thanks Romeo have removed it from the cordova plugin registry and updated the install instructions to use the git url.
