### ISSUE TITLE
Build Failed: no visible @interface for 'CDVPlugin' declares the selector 'initWithWebView:'

### ISSUE THREAD

**Issue by icfabo** [jamesla/backgroundvideo#14]
Hi,

when I compiling an error it occurs in the background.m file indicating the following:

backgroundvideo.m:15:37: error: 
      no visible @interface for 'CDVPlugin' declares the selector 'initWithWebView:'
    self = (backgroundvideo*)[super initWithWebView:theWebView];
                                            ~~~~~ ^~~~~~~~~~~~~~~

Any idea why this error can occur?

My cordova version: 6.2.0
My iOS platform version: 4.1.1

Thanks in advance,

Iñaki

**Comment by jamesla** [comment]
Hi I've just fixed this now so feel free to pull down the project and try again.

**Comment by icfabo** [comment]
Sorry, I thought I had answered you.

It now works fine.

Thanks
