### ISSUE TITLE
Testing in Phonegap Mobile App

### ISSUE THREAD

**Issue by adsonvinicius** [jamesla/backgroundvideo#15]
Does anyone has tested in Phonegap Mobile App for iOS? I've followed the steps, the demo page shows but when click on buttons, nothing happened, then i dont know if this plugins does not work anymore or is just a bug in phonegap mobile app.

Thanks in advance

**Comment by andresPereira** [comment]
Yes I do. The plugin in my case worked with the version ios 3.9.2.

**Comment by adsonvinicius** [comment]
I see, but in my case just the deviceready event has fired. So this plugin is not working anymore for ios 9.3.3....

**Comment by jamesla** [comment]
Hi Adson I just ran the demo on 9.3.5 on an iphone 6s and it worked fine. What device are you running?

**Comment by adsonvinicius** [comment]
I tested in phonegap mobile app, and nothing appears. But one question: this plugin allows me see what is recording inside my app? I mean, without call the iphone recording app?

**Comment by jamesla** [comment]
Hi Adson does the demo project work for you?

**Comment by adsonvinicius** [comment]
No man, it does not worked.

Adson

**Comment by jamesla** [comment]
Does the app run?

**Comment by adsonvinicius** [comment]
I tried using a phonegap app for it.

Adson

2016-09-15 22:11 GMT-03:00 James McCallum notifications@github.com:

**Comment by jamesla** [comment]
Hey sorry adson i dont think backgroundvideo supports what you are trying to achieve.
