### ISSUE TITLE
About the video quality

### ISSUE THREAD

**Issue by berserker001** [jamesla/backgroundvideo#17]
At the first,I have to say thank you.
I have try to used your plugin and I found a question.
The video quality is so low.

**Comment by jhayward** [comment]
the plugin doesn't currently have a setting for changing the quality and selects the low quality profile by default. as in VideoOverlay.java line ~94

```java
CamcorderProfile profile;
if (CamcorderProfile.hasProfile(mCameraId, CamcorderProfile.QUALITY_LOW)) {
    profile = CamcorderProfile.get(mCameraId, CamcorderProfile.QUALITY_LOW);
} else {
    profile = CamcorderProfile.get(mCameraId, CamcorderProfile.QUALITY_HIGH);
}
```
