### ISSUE TITLE
Camera not opening

### ISSUE THREAD

**Issue by OlegWarkentinWeb** [jamesla/backgroundvideo#18]
Hay, I try to use this plugin on my iphone 5S.

I have a simple start function, but the camera dont open. 

Maybe i need a permission? Or is the plugin not working anymore?

regards
Oleg

**Comment by jamesla** [comment]
Hi Oleg yes it is usage permissions. I have just added a hot fix that will add defaults but ultimately you will probably want to add your own for NSMicrophoneUsageDescription and NSCameraUsageDescription in your plist file.

Remove and add the plugin and you should be working again.
