### ISSUE TITLE
Can we change the opacity?

### ISSUE THREAD

**Issue by bolotkalil** [jamesla/backgroundvideo#19]
Hi, how we can change value of opacity?
Can we change opacity like css for example: from 0.1 to 1? 

Many thanks,
Bolot.

**Comment by andresPereira** [comment]
Hi, in android search the file  BackgroundVideo.java and change the value in the function containerView.setAlpha(0.2f); or in ios in the file backgroundvideo.m variable view.alpha.

**Comment by bolotkalil** [comment]
Thank you for the your answer andresPereira. how we can change the recording quality? in default very low quality.

**Comment by jhayward** [comment]
Hi, for android in file VideoOverlay.java around line 93 it sets the quality of the recording
and ios backgroundvideo.m around line 55.

**Comment by bolotkalil** [comment]
Many thanks guys.
