### ISSUE TITLE
Problem installing on cordova 7.0.1 - cordova-ios 4.4.0

### ISSUE THREAD

**Issue by erpxit** [jamesla/backgroundvideo#22]
Hello im not able to install this cool plugin on my app since i updated cordova framework to the latest release.

this is the output i get from installing command:

cordova plugin add https://github.com/jamesla/backgroundvideo.git

Error: Failed to fetch plugin https://github.com/jamesla/backgroundvideo.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: npm: Command failed with exit code 235 Error output:
npm ERR! addLocal Could not install /var/folders/69/9dttbrc57b516q7bw5w1jp0c0000gn/T/npm-56098-41ca62ac/git-cache-00543ecd/e2f493749b97076f173e3d7f7f82386f230de64f
npm ERR! code EISDIR
npm ERR! errno -21
npm ERR! syscall read
npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

┌────────────────────────────────────────────────────────────┐
│                  npm update check failed                   │
│            Try running with sudo or get access             │
│            to the local update config store via            │
│ sudo chown -R $USER:$(id -gn $USER) /Users/falcone/.config │
└────────────────────────────────────────────────────────────┘

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/falcone/.npm/_logs/2017-05-26T17_00_13_031Z-debug.log

thank you!

**Comment by erpxit** [comment]
plase some news hot to use plugin with cordova ios@4.4.0 ???

**Comment by jamesla** [comment]
I'll take a look this week

**Comment by erpxit** [comment]
Thank you so much, is it possible to offer you a beer ?

**Comment by jamesla** [comment]
Fixed in master

**Comment by erpxit** [comment]
works like a charm... you cool.  thank you for this great plugin.
