### ISSUE TITLE
does it record?

### ISSUE THREAD

**Issue by akyata** [jamesla/backgroundvideo#4]
The camera for video starts and I can stop it. I cant find any recorded file on the mobile. Does it record it?

**Comment by jhayward** [comment]
Yes - the video is currently saved into the app’s data directory ( Internal Storage ). 
The directory can be accessed using the cordova file plugin property - cordova.file.dataDirectory
eg. for android the path would be: /data/data/{ APP_NAMESPACE }/files/{ Name }.mp4

**Comment by akyata** [comment]
thanks 

Date: Mon, 27 Apr 2015 18:36:25 -0700
