### ISSUE TITLE
Testing backgroundvideo plugin

### ISSUE THREAD

**Issue by ghost** [jamesla/backgroundvideo#5]
Hi there, I'm currently building an app with this plugin and am trying to test it using the phone gap developer app. However I'm getting the following error when calling the start() function:

Error: undefined is not an object (evaluating 'window.Plugin.backgroundvideo.start')

I was just wondering if you guys had any experience testing this plugin with the phonegap developer app at all, would you expect it to work? Cheers

**Comment by jhayward** [comment]
Hi, please try updating the plugin and let us know if you still have the issue. cheers

**Comment by ghost** [comment]
Ok, I downloaded and updated the plugin locally as it seems the codebase available from the Cordova registry is outdated, still no luck.

**Comment by ytarek** [comment]
@DBSalvia , could you solve that problem ?

**Comment by ghost** [comment]
@ytarek no I couldn't, I'm in the process of trying to get my boss to purchase an ios developer account so I can test the plugin from within a natively packaged app, but otherwise I just receive this error:

Error: undefined is not an object (evaluating 'window.Plugin.backgroundvideo.start')

**Comment by oliverholmberg** [comment]
If you are running your source in the browser like a webpage (which is
useful for viewing layouts but not much else), plugins that use native
hardware features will not load or work.

If iOS is a target, you won't get very far without a developer license and
a device to test on.

**Comment by ytarek** [comment]
@DBSalvia  hey , any update about your progress ? , does the plugin work on android or are there any bugs ? , can you describe the plugin experience since it is not described in the index . does the camera open and start recording instantly or is there a start and stop button ? ,are there any camera controls before recording  ?

thanks
