### ISSUE TITLE
Overlay reappears

### ISSUE THREAD

**Issue by dairejpwalsh** [jamesla/backgroundvideo#9]
Hi when I call stop record function the overlay disappears as expected. However when I open the camera to capture an image using the media-capture plugin after having already taking a video recording the overlay reappears and my whole app becomes transparent again. I'm using a Samsung S6 running android version 5.1.1 for testing. Do you what may be causing this behaviour .

**Comment by jhayward** [comment]
The preview is started when the view (overlay) triggers surfaceCreated. Without looking, I would say that surfaceCreated is being triggered on resume your app.

**Comment by icfabo** [comment]
Hi,

In my application the same issue occurs.

I start recording and I stop recording. Then I send the app to the background or lock the screen and when I bring the app back to the foreground, the overlay reappears and my whole app becomes transparent again.

Any idea why this issue can occur?

Thanks in advance,

Iñaki

**Comment by jhayward** [comment]
What is your device and does a different device have the same issue?

**Comment by icfabo** [comment]
I have the issue in a BQ Aquaris 3.5 with Android 4.2.2 and in a LG Bello with Android 4.4.2.

My cordova version: 6.4.0
My Android platform version: 5.0.0

But with previous versions of cordova and android platform the issue was already produced.
